### ISSUE TITLE
Question - do you have a discord or slack for community development ?

### ISSUE THREAD

**Issue by Talador12** [Kristoferhh/WarlockSimulatorWOTLK#10]
I would like to help make code contributions and support in any way I can. I cannot find a roadmap of what still needs to be worked on, but that could be a good place to start for a community development channel. Maybe we can get one added to the warlock discord? What do you think? @Kristoferhh

**Comment by Kristoferhh** [comment]
We've created a #sim-development channel on the warlock discord 👌
