### ISSUE TITLE
TBC Items not showing up

### ISSUE THREAD

**Issue by Erodraeda** [Kristoferhh/WarlockSimulatorWOTLK#19]
No TBC items are showing up, even with the option marked.

That and P1 shows every item, but I assume that's a wowhead thing

**Comment by Kristoferhh** [comment]
I'm probably just gonna remove the TBC option and put TBC items in phase 1 since I'm only gonna have the bis tbc items in anyway.
I'll fix the phases for the WOTLK items when wowhead updates it 😃
